### ISSUE TITLE
Fatal error:

### ISSUE THREAD

**Issue by ulamnet** [andreas83/SocialNetwork#37] opened 2016-03-03 00:37 UTC
Hey , it's me again :)

ı get this error ;

Fatal error: Uncaught exception 'PDOException' with message 'invalid data source name' in /home/kimmoda/public_html/app/lib/database/dbpdo.php:20 Stack trace: 0 /home/kimmoda/public_html/app/lib/database/dbpdo.php(20): PDO->__construct('localhost;dbnam...', 'kimmoda\x1F_4', '23jemreulam', Array) 1 /home/kimmoda/public_html/app/lib/database/dbhandler.php(31): DBPDO->initDB() 2 /home/kimmoda/public_html/app/lib/database/dbtrait.php(52): DBHandler->__construct() 3 /home/kimmoda/public_html/app/lib/BaseModel.php(22): BaseModel->load_database_handler() 4 /home/kimmoda/public_html/app/controller/DataController.php(137): BaseModel->__construct()  5 /home/kimmoda/public_html/routing.php(98): DataController->stream(Array) 6 /home/kimmoda/public_html/init.php(7): include_once('/home/kimmoda/p...') 7 /home/kimmoda/public_html/index.php(9): require_once('/home/kimmoda/p...') 8 {main} thrown in /home/kimmoda/public_html/app/lib/database/dbpdo.php on line 20

**Comment by ulamnet** [comment] 2016-03-03 00:43
try my site ı m not sharing any

http://kimmoda.com/

**Comment by andreas83** [comment] 2016-03-03 07:37
your site "kimmoda.com" is working for me...  
does this "bug" still affects you, are is it solved ?

**Comment by ulamnet** [comment] 2016-03-03 07:39
after photo share get this error ;

Warning: move_uploaded_file(/home/lissi/tmp/dmdn/trunk/public/upload/56d7e9f782cea9.69755455_giphy.gif): failed to open stream: No such file or directory in /home/kimmoda/public_html/app/controller/DataController.php on line 336

Warning: move_uploaded_file(): Unable to move '/tmp/phpxXvw5f' to '/home/lissi/tmp/dmdn/trunk/public/upload/56d7e9f782cea9.69755455_giphy.gif' in /home/kimmoda/public_html/app/controller/DataController.php on line 336

Warning: Creating default object from empty value in /home/kimmoda/public_html/app/controller/DataController.php on line 338

Warning: mime_content_type(/home/lissi/tmp/dmdn/trunk/public/upload/56d7e9f782cea9.69755455_giphy.gif): failed to open stream: No such file or directory in /home/kimmoda/public_html/app/controller/DataController.php on line 340

Warning: Creating default object from empty value in /home/kimmoda/public_html/app/controller/DataController.php on line 342

Warning: Cannot modify header information - headers already sent by (output started at /home/kimmoda/public_html/app/controller/DataController.php:336) in /home/kimmoda/public_html/app/lib/BaseController.php on line 75

**Comment by andreas83** [comment] 2016-03-03 08:34
you need to modify the upload path 
replace this
`dir="/home/lissi/tmp/dmdn/trunk";`
with 
`dir="/home/kimmoda/public_html";`

also make sure that /home/kimmoda/public_html/public/upload is writeable by webserver

depending on your system this can be done by: 

`sudo chown www-data:www-data -R /home/kimmoda/public_html/public/upload`

**Comment by ulamnet** [comment] 2016-03-03 08:40
now ı get this error .s 


Warning: Creating default object from empty value in /home/kimmoda/public_html/app/controller/DataController.php on line 338

Warning: Creating default object from empty value in /home/kimmoda/public_html/app/controller/DataController.php on line 342

Warning: Cannot modify header information - headers already sent by (output started at /home/kimmoda/public_html/app/controller/DataController.php:338) in /home/kimmoda/public_html/app/lib/BaseController.php on line 75

**Comment by ulamnet** [comment] 2016-03-03 11:09
images sucessfull upload , but before uploading get this error : 

Warning: Creating default object from empty value in /home/kimmoda/public_html/app/controller/DataController.php on line 338

Warning: Creating default object from empty value in /home/kimmoda/public_html/app/controller/DataController.php on line 342

Warning: Cannot modify header information - headers already sent by (output started at /home/kimmoda/public_html/app/controller/DataController.php:338) in /home/kimmoda/public_html/app/lib/BaseController.php on line 75

**Comment by ulamnet** [comment] 2016-03-03 16:40
are you there?

**Comment by andreas83** [comment] 2016-03-03 16:54
yep, looks like a bug, i will fix it as soon as i can.

**Comment by ulamnet** [comment] 2016-03-03 16:57
okay, thanks for reply.

**Comment by andreas83** [comment] 2016-03-03 16:58
okay fixed, please checkout and test

**Comment by ulamnet** [comment] 2016-03-03 16:59
where is the fixed ı dont see

**Comment by andreas83** [comment] 2016-03-03 16:59
4335458d0bf30cddd0c910f870b9cca85f41384d

**Comment by ulamnet** [comment] 2016-03-03 17:02
Warning: Creating default object from empty value in /home/kimmoda/public_html/app/controller/DataController.php on line 327

Warning: Cannot modify header information - headers already sent by (output started at /home/kimmoda/public_html/app/controller/DataController.php:327) in /home/kimmoda/public_html/app/lib/BaseController.php on line 75

**Comment by andreas83** [comment] 2016-03-03 17:37
please let me know which url did you try to share ?

**Comment by ulamnet** [comment] 2016-03-03 17:41
http://kimmoda.com/

**Comment by andreas83** [comment] 2016-03-03 17:52
mhm strange, try to pull latest changes again. 
if the bug still exists, please write me the exact steps to reproduce it.

thx

**Comment by ulamnet** [comment] 2016-03-03 18:15
I try your saying , but now get this error ; 
Fatal error: Can't use function return value in write context in /home/kimmoda/public_html/app/controller/DataController.php on line 271

**Comment by ulamnet** [comment] 2016-03-03 20:13
Are you there?

**Comment by andreas83** [comment] 2016-03-03 20:22
jepp iam here. 
whats on line 271 ? 
i just wonder, because i dont get these error...

**Comment by andreas83** [comment] 2016-03-03 20:24
sry now i get the same error on prod envir .... strange

**Comment by andreas83** [comment] 2016-03-03 20:31
this line cause the error.. 
`isset($_POST['metadata']) && empty(json_decode($_POST['metadata']))` 
for some strange reasons, only on prod and your system, this line
works pretty fine on my local dev enviroment ....  
@besn @chilimatic any hints?

**Comment by andreas83** [comment] 2016-03-03 20:40
found the cause:

> Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.

via https://beeznest.wordpress.com/2014/09/26/cant-use-function-return-value-in-write-context/

**Comment by andreas83** [comment] 2016-03-03 20:42
okay fixed, please test again

**Comment by ulamnet** [comment] 2016-03-03 21:07
I tested my friend but still this error :(

Warning: Creating default object from empty value in /home/kimmoda/public_html/app/controller/DataController.php on line 324

Warning: Cannot modify header information - headers already sent by (output started at /home/kimmoda/public_html/app/controller/DataController.php:324) in /home/kimmoda/public_html/app/lib/BaseController.php on line 75

http://kimmoda.com/

**Comment by ulamnet** [comment] 2016-03-03 21:12
and after uploading any share , not showing in site.

**Comment by chilimatic** [comment] 2016-03-03 21:52
@andreas83 this is just the typecast warning which causes the http headers to be sent early.
            if (isset($metadata->type) && $metadata->type == "www") {
               $metadata=(object)($this->og_parser($metadata->url));
            }
just add the stfu operator @ before it or add the check :D

**Comment by andreas83** [comment] 2016-03-03 22:12
not sure if its the typecasting, since the warning happens on 324 
which is the if statement itself...

**Comment by chilimatic** [comment] 2016-03-03 22:16
ahh misread the line, thx :) so $metadata= NULL; -> $metadata = new stdClass() ? :)

**Comment by andreas83** [comment] 2016-03-03 22:26
for me this make no sense at all. 
$metadata is either NULL or an object.... 
with error reporting on, this does not create any warning.. 

`$test=NULL;

if(isset($test) && $test->x=="y")
{
        echo "foobar";
}`

**Comment by andreas83** [comment] 2016-03-03 22:29
sorry guys, but i have to go now.
since i will be in Germany for a couple of days, i will not be able to support you until Tuesday!

**Comment by chilimatic** [comment] 2016-03-03 22:51
maybe its php version related ? dunno :) hf see u next week :)

**Comment by ulamnet** [comment] 2016-03-08 10:56
@andreas83 are you there ? :)

**Comment by andreas83** [comment] 2016-03-08 22:49
yepp just arrived today, lets track this error down ;)

**Comment by ulamnet** [comment] 2016-03-09 07:03
sorry , ı don't understand.

**Comment by andreas83** [comment] 2016-03-09 17:11
@ulamnet  which php version are you running ?

**Comment by andreas83** [comment] 2016-03-09 17:12
@ulamnet if possible, you could send me the server credentials (login) and i try to fix on your webserver.

**Comment by ulamnet** [comment] 2016-03-09 17:47
yes its possible , but how to send?

**Comment by andreas83** [comment] 2016-03-09 21:04
just send it to andreas at moving-bytes.at

**Comment by andreas83** [comment] 2016-03-11 11:50
@ulamnet still waiting for your credentials

**Comment by ulamnet** [comment] 2016-03-11 15:29
sorry , you can write your mail adress ? I send login credentials with mail

**Comment by andreas83** [comment] 2016-03-12 23:39
i did already ...   andreas@moving-bytes.at

**Comment by ulamnet** [comment] 2016-03-13 20:50
Okay , ı send.

**Comment by ulamnet** [comment] 2016-03-14 00:14
@andreas83 are you there?

**Comment by andreas83** [comment] 2016-03-14 14:56
@ulamnet yep iam here, its fixed :)  thanks for reporting

**Closed by andreas83** 2016-03-14 14:56 UTC
